### ISSUE TITLE
Draperbundle, issue when deleting "no profile" and "has profile" roles

### ISSUE THREAD

**Issue by evacfk** [Drapersniper/drapercogs#5]
Console endlessly spams the error below when those two roles are removed.

`Ignoring exception in on_member_update
red       | Traceback (most recent call last):
red       |   File "/data/venv/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
red       |     await coro(*args, **kwargs)
red       |   File "/data/cogs/CogManager/cogs/draperbundle/gamingprofile.py", line 318, in on_member_update
red       |     await update_member_atomically(
red       |   File "/data/cogs/CogManager/cogs/draperbundle/utilities.py", line 816, in update_member_atomically
red       |     return await member.edit(roles=roles)
red       |   File "/data/venv/lib/python3.8/site-packages/discord/member.py", line 578, in edit
red       |     await http.edit_member(guild_id, self.id, reason=reason, **payload)
red       |   File "/data/venv/lib/python3.8/site-packages/discord/http.py", line 221, in request
red       |     raise Forbidden(r, data)
red       | discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
red       | Ignoring exception in on_member_update
red       | Traceback (most recent call last):
red       |   File "/data/venv/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
red       |     await coro(*args, **kwargs)
red       |   File "/data/cogs/CogManager/cogs/draperbundle/gamingprofile.py", line 318, in on_member_update
red       |     await update_member_atomically(
red       |   File "/data/cogs/CogManager/cogs/draperbundle/utilities.py", line 816, in update_member_atomically
red       |     return await member.edit(roles=roles)
red       |   File "/data/venv/lib/python3.8/site-packages/discord/member.py", line 578, in edit
red       |     await http.edit_member(guild_id, self.id, reason=reason, **payload)
red       |   File "/data/venv/lib/python3.8/site-packages/discord/http.py", line 221, in request
red       |     raise Forbidden(r, data)
red       | discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
red       | Ignoring exception in on_member_update
red       | Traceback (most recent call last):
red       |   File "/data/venv/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
red       |     await coro(*args, **kwargs)
red       |   File "/data/cogs/CogManager/cogs/draperbundle/gamingprofile.py", line 318, in on_member_update
red       |     await update_member_atomically(
red       |   File "/data/cogs/CogManager/cogs/draperbundle/utilities.py", line 816, in update_member_atomically
red       |     return await member.edit(roles=roles)
red       |   File "/data/venv/lib/python3.8/site-packages/discord/member.py", line 578, in edit
red       |     await http.edit_member(guild_id, self.id, reason=reason, **payload)
red       |   File "/data/venv/lib/python3.8/site-packages/discord/http.py", line 221, in request
red       |     raise Forbidden(r, data)
red       | discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
red       | [2020-03-27 15:12:14] [INFO] red.drapercogs.button_channel: Running channel_cleaner
red       | [2020-03-27 15:12:14] [INFO] red.drapercogs.button_channel: Running channel_cleaner
`

**Comment by Drapersniper** [comment]
@evacfk  Are you on the latest version?

**Comment by Drapersniper** [comment]
Closing as stale
