### ISSUE TITLE
[Gprofile] Add Option 

### ISSUE THREAD

**Issue by Menteroth** [Drapersniper/drapercogs#9]
Make using region roles an option because it collides with already setup region roles for the server if a member does not have a gaming profile setup.

**Comment by Drapersniper** [comment]
Addressed in https://github.com/Drapersniper/drapercogs/commit/3d6ace6b9f4b82d1b60361d152bc9486aad46039

**Comment by Menteroth** [comment]
Nice thanks. Was a bit slow with the issue.

Also, if you wanna correct the response.
`-` Gamming profile will not longer touch user roles
`+` Gaming profile will no longer touch user roles.
